### ISSUE TITLE
Name of the current print changes if you upload another model to storage during print

### ISSUE THREAD

**Issue by tysonsw** [prusa3d/Prusa-Link-Web#401] opened 2023-05-02 14:47 UTC
The name of the current print in the Dashboard in Prusa Link Beta changes to the last uploaded model to the storage. The display on the printer shows the correct information.
Steps to reproduce:

1. Start a print of a model called "batch1". The Dashboard will show the correct name for the model "batch1".
2. Upload a print called "batch2" to the storage with the webinterface or with PrucaSlicer.  The Dashboard will change the name of the model that is being printed to "batch2".

Doesn't matter which device opens the dashboard after the upload. All devices will see the wrong name.

Printer: Prusa Mini+
Firmware: 4.4.1
Web browser: Firefox

**Comment by Prusa-Support** [comment] 2023-05-03 13:12
Thanks for reporting.

We are aware of this.
Please let me close this issue as duplicate of https://github.com/prusa3d/Prusa-Link-Web/issues/268.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-05-03 13:12 UTC
