### ISSUE TITLE
PRUSA Link: USB-Stick - No Directories Visible / changeable 

### ISSUE THREAD

**Issue by KlausKraemer** [prusa3d/Prusa-Link-Web#340] opened 2023-01-16 06:32 UTC
To keep the USB stick practical, it's necessary to put projects into subdirectories. E.g. first choice is Material and so on.

These directories aren't supported by PRUSA Link. You can only access the root directory. Directly on the MINI+ thex can be accessed.

Please make directories on the USB stick also accessible in PRUSA Link.

**Comment by ondratu** [comment] 2023-01-20 09:35
Hi, yes, that is one of next other functionalities which we plan to next release.

**Comment by Prusa-Support** [comment] 2023-02-08 19:07
Please allow me to close this issue as a duplicate of https://github.com/prusa3d/Prusa-Link-Web/issues/290.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-02-08 19:07 UTC
Labels: feature request, MINI/+
