### ISSUE TITLE
Prusa-Link - Currently Printing Filename displayed on Dashboard gets replaced by Filename sent to printer over Wifi

### ISSUE THREAD

**Issue by re490** [prusa3d/Prusa-Link-Web#355] opened 2023-02-09 19:38 UTC
A minor Quirk/Bug:

If you send a file using WiFi from PrusaSLicer 2.50 to Prusa-Link  (Prusa MINI+, latest firmware 4.4.1) while it is printing a file, then the currently displayed Filename on the Dashboard gets replaced with the name of the file that was sent to the printer instead of the name of the file that is printing.   The image remains unchanged and shows the currently printing gcode file.

**Comment by Prusa-Support** [comment] 2023-03-11 16:03
Thanks for reporting. This issue was already posted though.

Please allow me to close it as duplicate of issue https://github.com/prusa3d/Prusa-Link-Web/issues/268.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-03-11 16:03 UTC
