### ISSUE TITLE
When uploading a file while something is printing, the filename in API and WEB changes

### ISSUE THREAD

**Issue by LucaMH** [prusa3d/Prusa-Link-Web#385] opened 2023-03-29 20:05 UTC
Hi,

i just found this out by "accident"..
When uploading a file via web or Slicer while something is printing, the filename in the Dashboard and the API changes to the last uploaded.

Printer is a PrusaMINI+ with 4.4.0+4180
Regards,
Luca

**Comment by Prusa-Support** [comment] 2023-05-03 13:12
Thanks for reporting.

We are aware of this.
Please let me close this issue as duplicate of https://github.com/prusa3d/Prusa-Link-Web/issues/268.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-05-03 13:12 UTC
