### ISSUE TITLE
TCP thread - precise data access error

### ISSUE THREAD

**Issue by skierX1** [prusa3d/Prusa-Link-Web#316] opened 2022-12-07 14:43 UTC
- Printer Mini+, upgraded to the 4.4.0+4180 firmware, wifi module not installed yet.
- gcode file uploaded directly from the slicer, checked again directly on usb drive, the file content is correct,
- The print was started directly from the printer (not from the slicer and after the printer was reset),
- Ethernet cable was plugged in at the time of crash.
- One browser window with prusalink (printer address) was opened in the macOS safari browser, window untouched for couple of hours, not even connected as the prusalink api key was still not entered.
![20221207_145602](https://user-images.githubusercontent.com/30984768/206208869-998566ae-2a2f-42cc-92c5-935224057142.jpg)

**Comment by Prusa-Support** [comment] 2022-12-29 20:03
Thanks for reporting this.

So the uploading process apparently went smoothly. This may be a problem with the printer unrelated to Prusa Link. If this is confirmed, the issue can be moved to [prusa3d/Prusa-Firmware-Buddy](https://github.com/prusa3d/Prusa-Firmware-Buddy) repository.

Am I understanding correctly that BSOD would appear after:
1. uploading a file via Prusa Slicer; 
2. pressing the reset knob on the printer;
3. starting the print from the printer menu.

Please clarify if there are more steps strictly necessary for the reproducibility of the issue.
Also, please consider generating a Crash Dump (_settings > Save Crash Dump_) to be uploaded in this thread, after BSOD occurs.

Are you able to reproduce the issue with other .gcode files uploaded from Prusa Slicer via internet?
Are you able to reproduce the issue with the same .code file directly uploaded on the USB flash drive via computer?
Would the issue persist if Prusa Link is not opened from the browser?
Would it make a difference if the Ethernet cable is disconnected after the upload?
Are you able to reproduce the problem using a different USB flash drive?

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2023-01-24 19:58
This issue has been silent so far and we are missing the necessary data for reproducibility. 
As of now, this issue seems to be a duplicate of issues https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2837 or https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2640 concerning the Buddy firmware.

This issue will be closed for now.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-01-24 19:58 UTC
Labels: bug, can't reproduce, awaiting response, MINI/+
